version: "2"

linters:
  # standard = errcheck, govet, ineffassign, staticcheck, unused
  default: standard
  enable:
    - misspell
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/shadiramadan/kdelta
  exclusions:
    generated: lax
