apiVersion: v1
kind: Service
metadata:
  name: kdelta
  labels:
    app.kubernetes.io/name: kdelta
spec:
  selector:
    app.kubernetes.io/name: kdelta
  ports:
    - name: http
      port: 80
      targetPort: http
